package rainstar.abilitywar.ability;

import daybreak.abilitywar.ability.AbilityManifest;
import daybreak.abilitywar.ability.AbilityManifest.Rank;
import daybreak.abilitywar.ability.AbilityManifest.Species;

@AbilityManifest(name = "사일런트", rank = Rank.L, species = Species.HUMAN, explain = {
		"oew3gzXJOYMyojeDMaU1IKHsYy0goew4gzLhOYMynjih7GY6IKHsM6HsboM0zjODMNo4oexmgzLuMyCCN9s1gzCzOSCCOYY3gzHqOIMy7jOCN901gzHzOSCh7DeDM5UxgzKjMaHsZoM2hTaCOYExgjmDOS4KIII4xzGDMK43IIMw8TGCOfk1gzGJNYMz1TEggzLgOYI4+TkggjmGN4Mx6jiDMu4zgjfdNSCDM8E1gjj5OSCDNoExgzaGN4MwgzKDM5ozIKHsYzE1JaHsZiCDM9E2gjfPNYM2hTaCOYExgjmDOS4Koew3gjiEM4MzqjAggjfoMII34DQgoexjLSCh7DODM6o0gzOoNKHsZjoggjiEM4MzqjAggjfoMII34DQggzKiN4MwtjOCOYM5III5hjeDMeo4gzLuM4I33TUgoexlgzXoN4Myojih7GaDM5U1IIMxlzWDMvExgzaFNoI5gTGCOYM5LiCh7GWDNeg3gzKiOKHsZoMzlTEggjmGN4Mx6jiDM5c1IIMyojeDMuU5gzCuNwoggzaEM4MyjzWCN885IKHsNYI35TmDM6o0oexmgzKiN4M1iTWCN+U5LDSDMPw3gzPaNyCh7GWDNeg3gzKiOKHsZoMzmjMggzKoMoMzmjODMMc1III5hjeDMeo4gzOVNSAzLjCDNKsxgjfPOSCh7DOh7G6DNM4zgzDaOKHsZoMyojeDNYsygjmBMYI5gzkuCiCCOYY3gzHqOIMzmjMggjjHMYMwrjcggjfoMII34DSDNoQzgjmDOYMwxzUgoexlgzXoN4Myojih7GaDM5UxIIM0qzGCOIk1gzadMYI5pDSCOYExgjmDOS4goexjgzOROYI5gzCDMYQ3IIM09DeDNYwzgzObOSCh7Dc6IKHsZjE1gzSrMQqh7DeDNKA3gjfuMyCDM4Y3gzWEN4MwszYgoexjLSCh7DmDMus2gzOrMaHsZjoggzPBNYMxhDMgNi41gzTPOYI4yTkggzDMN4I5tjcggzX6M4MwiTWDM5ozgzLrNYMwrjcgNS4wgzSrMYI3zzkgoewzoexugzTOM4Mw2jih7GaDMqI3gzWLMoI5gTGCOYM5LiCh7GODNPQ3gzWMM4Mzmzkgoew3OiCh7GYzNYM0qzEKIDE1LjCDNKsxgjfPOSCCN901gzObOSCCOMk5IKHsM6HsboM0zjODMNo4oexmIIMx6jiDNY8xgzOdMSCDMo8xIKHBIKHsYjIwJaHsZoMwtjeDNYU1IKHsYoMzmjOCOZw0IIMygTKCOZozoexmgjfPNSCDM9E2gjfPNYM2hTaCOYExgjmDOS4goew4KKHsN4M0szWCOYY3IDEwMCWh7DgpCqHsOVuh7DODNM4zgzDaOKHsOV0goexhgzLjMoM1xDODMaU1oexmLCCh7DaDNYwzgjfdNYM1xjSh7GYggzKdMYM1ijODM5U1IIMx6DeDM4YwgzaENyCDMo8xIIMy7TODMp44gjmBMYI5gzku",
		"맞혀보든가 푸하하"
		},
		summarize = {
		""
		})
public class Silent {

}
